export const imagePaths = {
    Icon1: require('../components/images/smartphone.png'),
    Icon2: require('../components/images/Laptop.png'),
    Icon3: require('../components/images/Documents.png'),
    Icon4: require('../components/images/Jewel.png'),
    Icon5: require('../components/images/key.png'),
    Icon6: require('../components/images/id.png'),
    Icon7: require('../components/images/bottle.png'),
    Icon8: require('../components/images/lunchbox.png'),
    Icon9: require('../components/images/pencilcase.png'),
    Icon10: require('../components/images/clothes.png'),
    Icon11: require('../components/images/wallet.png'),
    Icon12: require('../components/images/umbrella.png'),
    Icon13: require('../components/images/backpack.png'),
    Item1: require('../components/images/Mcbook.jpeg'),
    Item2: require('../components/images/Iphone.jpg'),
    Item3: require('../components/images/Item3.jpg'),
    Item4: require('../components/images/Item4.jpg'),
    Item5: require('../components/images/Item5.jpg'),
    Item6: require('../components/images/Items2.jpg'),
    Item7: require('../components/images/Item7.jpg'),
    Item8: require('../components/images/Item8.jpg'),
    Item9: require('../components/images/Item9.jpg'),
    Item10: require('../components/images/item10.webp'),
    Item11: require('../components/images/Item11.jpeg'),
    Item12: require('../components/images/item12.webp'),
    Item13: require('../components/images/item13.webp'),
    Item14: require('../components/images/Item14.jpg'),
    Item15: require('../components/images/item15.webp'),
    heroimg: require('../components/images/hero.jpg'),
    Bannerimg: require('../components/images/Banner-img.png'),
    student1: require('../components/images/Student1.jpg'),
    student2: require('../components/images/Student2.jpg'),
    line1: require('../components/images/Line1.png'),
    line2: require('../components/images/Line 2.png'),
    imagehero: require('../components/images/Image-hero.png'),
    Weblogo: require('../components/images/Weblogo.png')

  };
  
  export default imagePaths;